version: "3.9"
services:
    producer:
       tty: true
       command: ["cat"]
       container_name: producer
       build:
         context: infrastructure/conan-docker
       volumes:
       - type: bind
         source: ./produce
         target: /home/conan/projects
    consumer:
       tty: true
       command: ["cat"]
       container_name: consumer
       build:
         context: infrastructure/conan-docker
       volumes:
       - type: bind
         source: ./consume
         target: /home/conan/projects
    artifactory:
        container_name: artifactory
        image: releases-docker.jfrog.io/jfrog/artifactory-cpp-ce:latest
        ports:
        - "8081:8081"
        - "8082:8082"
        volumes:
        - type: bind
          source: ${JFROG_HOME:-./}/artifactory/var
          target: /var/opt/jfrog/artifactory
          
