version: "3.9"
services:
    producer:
       tty: true
       command: ["cat"]
       container_name: producer
       image: conan:1.0
       volumes:
       - type: bind
         source: ./create_hello_package
         target: /project
    consumer:
       tty: true
       command: ["cat"]
       container_name: consumer
       image: conan:1.0
       volumes:
       - type: bind
         source: ./consume_hello_package
         target: /project
    artifactory:
        container_name: artifactory
        image: releases-docker.jfrog.io/jfrog/artifactory-cpp-ce:latest
        ports:
        - "8081:8081"
        - "8082:8082"
        volumes:
        - type: bind
          source: ${JFROG_HOME:-./}/artifactory/var
          target: /var/opt/jfrog/artifactory
          
